name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------
      # PYTHON LINT + TEST
      # -----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install flake8 pytest



      - name: Run unit tests
        env:
          PYTHONPATH: .  # Giúp pytest thấy được folder /app và /scripts
        run: |
          # Chạy cả 2 file test trong folder tests/
          pytest tests/test_api.py tests/test_preprocess.py -v

      # -----------------------------
      # Validate docker-compose file
      # -----------------------------
      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config

      # -----------------------------
      # Build Docker images
      # -----------------------------
      - name: Build Airflow image
        run: docker build -t airflow-ci ./airflow

      - name: Build MLflow image
        run: docker build -t mlflow-ci ./mlflow

      - name: Build FastAPI service image
        run: docker build -t fastapi-ci -f ./app/Dockerfile .
